# Generated by Django 5.2.17 on 2026-09-26 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cartitem',
            new_name='cart_cartit_cart_id_4fb076_idx',
            old_name='cart_cartitem_cart_id_idx',
        ),
    ]
