"""Canonical variant option pool for Neon/Postgres seed.

Kept as data (not hard-coded UI) so Admin reads definitions from the DB.
"""

from __future__ import annotations

# (key, label, kind, placeholder, suggestions, recommend_all, sort_order, category_slugs)
OPTION_SEED: list[tuple] = [
    (
        "color",
        "Color",
        "color",
        "e.g. Taupe, Navy",
        [
            "Taupe",
            "Navy",
            "White",
            "Ivory",
            "Cream",
            "Beige",
            "Grey",
            "Black",
            "Maroon",
            "Olive",
            "Brown",
            "Gold",
        ],
        True,
        10,
        ["shawls", "peshawari-chappals", "perfumes-fragrances"],
    ),
    (
        "size",
        "Size",
        "text",
        "e.g. S, M, L or Free size",
        ["XS", "S", "M", "L", "XL", "XXL", "Free size", "One size"],
        True,
        20,
        ["shawls"],
    ),
    (
        "volume",
        "Volume",
        "text",
        "e.g. 30ml, 50ml, 100ml",
        ["10ml", "15ml", "30ml", "50ml", "100ml", "3ml", "6ml", "12ml"],
        False,
        30,
        ["skincare", "perfumes-fragrances", "oral-care"],
    ),
    (
        "pack_size",
        "Pack size",
        "text",
        "e.g. Single, Duo, Pack of 2",
        ["Single", "Duo", "Pack of 2", "Pack of 3", "Pack of 4"],
        False,
        40,
        ["oral-care", "skincare"],
    ),
    (
        "flavor",
        "Flavor / taste",
        "text",
        "e.g. Mint, Charcoal, Unflavoured",
        ["Mint", "Peppermint", "Charcoal", "Clove", "Unflavoured"],
        False,
        50,
        ["oral-care"],
    ),
    (
        "bristle_firmness",
        "Bristle firmness",
        "text",
        "e.g. Soft, Medium",
        ["Extra soft", "Soft", "Medium", "Firm"],
        False,
        60,
        ["oral-care"],
    ),
    (
        "skin_type",
        "Skin type",
        "text",
        "e.g. All skin types, Oily, Dry",
        ["All skin types", "Dry", "Oily", "Combination", "Sensitive"],
        False,
        70,
        ["skincare"],
    ),
    (
        "texture",
        "Texture",
        "text",
        "e.g. Cream, Gel, Serum, Oil",
        ["Cream", "Gel", "Serum", "Lotion", "Oil", "Balm", "Foam"],
        False,
        80,
        ["skincare"],
    ),
    (
        "spf",
        "SPF",
        "text",
        "e.g. SPF 30, SPF 50",
        ["SPF 15", "SPF 30", "SPF 50", "SPF 50+"],
        False,
        90,
        ["skincare"],
    ),
    (
        "concentration",
        "Concentration",
        "text",
        "e.g. EDP, EDT, Attar, Oil",
        ["EDP", "EDT", "EDC", "Attar", "Perfume oil", "Body mist"],
        False,
        100,
        ["perfumes-fragrances"],
    ),
    (
        "scent_family",
        "Scent family",
        "text",
        "e.g. Woody, Floral, Oriental",
        ["Floral", "Woody", "Oriental", "Fresh", "Citrus", "Musk", "Oud", "Spicy"],
        False,
        110,
        ["perfumes-fragrances"],
    ),
    (
        "scent_note",
        "Key note",
        "text",
        "e.g. Oud, Rose, Jasmine",
        ["Oud", "Rose", "Jasmine", "Sandalwood", "Amber", "Vanilla", "Musk"],
        False,
        120,
        ["perfumes-fragrances"],
    ),
    (
        "material",
        "Material",
        "text",
        "e.g. Pashmina, Wool, Cotton",
        ["Pashmina", "Wool", "Cashmere", "Cotton", "Silk", "Blend", "Acrylic"],
        False,
        130,
        ["shawls", "peshawari-chappals"],
    ),
    (
        "weave",
        "Weave / finish",
        "text",
        "e.g. Handwoven, Embroidered",
        ["Handwoven", "Machine woven", "Embroidered", "Plain", "Jacquard"],
        False,
        140,
        ["shawls"],
    ),
    (
        "dimensions",
        "Dimensions",
        "text",
        "e.g. 70×200 cm",
        ["70×200 cm", "100×200 cm", "110×220 cm", "140×200 cm"],
        False,
        150,
        ["shawls"],
    ),
    (
        "footwear_size",
        "Footwear size",
        "text",
        "e.g. EU 40 / UK 6",
        [
            "EU 39",
            "EU 40",
            "EU 41",
            "EU 42",
            "EU 43",
            "EU 44",
            "EU 45",
            "UK 5",
            "UK 6",
            "UK 7",
            "UK 8",
            "UK 9",
            "UK 10",
        ],
        False,
        160,
        ["peshawari-chappals"],
    ),
    (
        "sole",
        "Sole",
        "text",
        "e.g. Single sole, Double sole, Tire sole",
        ["Single sole", "Double sole", "Tire sole", "Leather sole", "Rubber sole"],
        False,
        170,
        ["peshawari-chappals"],
    ),
    (
        "upper",
        "Upper",
        "text",
        "e.g. Leather, Suede",
        ["Leather", "Suede", "Nubuck", "Fabric"],
        False,
        180,
        ["peshawari-chappals"],
    ),
    (
        "finish",
        "Finish",
        "text",
        "e.g. Matte, Gloss, Natural",
        ["Matte", "Gloss", "Natural", "Distressed", "Polished"],
        False,
        190,
        ["peshawari-chappals", "shawls"],
    ),
    (
        "count",
        "Unit count",
        "text",
        "e.g. 1 brush, 100 tablets",
        ["1", "2", "3", "4", "50", "100"],
        False,
        200,
        ["oral-care", "skincare"],
    ),
]
