# Generated by Django 5.2.17 on 2026-09-26 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_cancelled_status'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_custome_413d7d_idx',
            old_name='orders_order_customer_created_idx',
        ),
    ]
