# Generated by Django 5.2.17 on 2026-09-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_guest_order_contact_and_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier_name',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='order',
            name='courier_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='courier_tracking_number',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('MANUAL_TRANSFER', 'Bank / wallet transfer'), ('CASH_ON_DELIVERY', 'Cash on delivery')], default='MANUAL_TRANSFER', max_length=32),
        ),
    ]
