# Generated by Django 5.2.17 on 2026-09-28 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_catalog_cat_slug_695af4_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantOptionDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('kind', models.CharField(choices=[('text', 'Text'), ('color', 'Color')], default='text', max_length=16)),
                ('placeholder', models.CharField(blank=True, default='', max_length=160)),
                ('suggestions', models.JSONField(blank=True, default=list)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('recommend_all', models.BooleanField(default=False, help_text='When true, surface this option for every category.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'label'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='catalog_var_is_acti_b07308_idx')],
            },
        ),
        migrations.CreateModel(
            name='CategoryOptionRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_recommendations', to='catalog.category')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_links', to='catalog.variantoptiondefinition')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('category', 'option'), name='uniq_category_option_recommendation')],
            },
        ),
    ]
